services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: kurdish-backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
        ASPNETCORE_ENVIRONMENT: Production
        ASPNETCORE_URLS: http://+:8080
        ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=KurdishDictionary;User Id=kurdish_user;Password=${SQL_USER_PASSWORD};TrustServerCertificate=True;"
    ports:
      - "6000:8080"
    networks:
      - kurdish-net
    restart: unless-stopped

  frontend-blazor:
    build:
      context: .
      dockerfile: frontend-blazor/Dockerfile
    container_name: kurdish-blazor
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "6001:8080"
    depends_on:
      - backend
    networks:
      - kurdish-net
    restart: unless-stopped

  frontend-nextjs:
    build:
      context: ./frontend-nextjs
      dockerfile: Dockerfile
    container_name: kurdish-nextjs
    environment:
      NODE_ENV: production
      API_URL: http://backend:8080
    ports:
      - "4000:4000"
    depends_on:
      - backend
    networks:
      - kurdish-net
    restart: unless-stopped

networks:
  kurdish-net:
    driver: bridge
